# Generated by Django 3.2.16 on 2022-12-24 21:25

from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('date_added', models.DateField()),
                ('url', models.URLField()),
                ('pdf_file', models.FileField(upload_to='')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('paper'), models.Model),
        ),
    ]
